FROM mhart/alpine-node

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY node_modules /usr/src/app/node_modules
COPY dist /usr/src/app/dist
COPY sample /usr/src/app/sample
COPY package.json /usr/src/app

EXPOSE 3000

CMD [ "npm", "start" ]
