FROM daocloud.io/zzq889/alpine-node-yarn

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
COPY yarn.lock /usr/src/app/
RUN yarn install

COPY . /usr/src/app
RUN npm run build

RUN rm -rf node_modules
RUN yarn install --prod
RUN tar zcvf dist.tar.gz dist node_modules sample package.json
